workflows:
  android-release:
    environment:
      flutter: 3.13.1
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
